name: ${project.artifactId}
main: me.jaden.tag.Tag
version: ${project.version}
author: [Jaden Giordano]

commands:
  buy:
    description: Buy items!
    usage: /<command> [item name]
  tags:
    description: Show how many tags you have.
    usage: /<command>
